language: R
services:
- docker
cache: packages
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libhiredis-dev libzmq3-dev
- sudo mv /usr/include/hiredis/* /usr/include/
install:
- R -e 'devtools::install_deps(dep=T)'
script:
- R CMD build .
- R CMD check *tar.gz
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_COMMIT_MESSAGE" == "version bump" ]]; then
  docker build -t lecardozo/rworker:latest \ -t lecardozo/rworker:"$TRAVIS_TAG" ./docker ; 
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push lecardozo/rworker;
  fi
env:
  global:
    DOCKER_USERNAME:
      secure: mJqtQ5h8iYnRIKzWYl0X++YfpTlgtG9mtVu9cBAY3Bb04pKQW1Y+VUL0tfwgUi6ZpAAr9NnYhqbn1fxRUPp//GFxlPQ8xsqLpCqOM+JN+2My/ROvFYBOB9bchKMdq9u7kW30LoJFn321VGa4jYz2O/cQkXfU/W9rG6WxbkI/gl1aRzcNYAGcZRqiQF4c9w6T0YGNqONAtbHLm+2j5oPt7fHQGSCHXG2o7M2ljaIgPtsHnnOFp/vhxvkcM/XGaiZkqKSEYGeGfEzJ/ungdBQt5fGk2Emq3F45zN+y7GapK8HtUgKqT2Y57YnLGuApLCzpoc8RJxZ3TIy4FqVgD5I/E9T1l57lpWhFDF34S6dyGZGxYwIcWT9LdIU8x0DnV93GwJ9NQV5FMXj0FPjwRr1XY7gCl2LVEna+AjwfIybBGsFodrZiYpdS440YKTwaLNSe7zRbDeNNhMZDGavzk4NOWYpPLixlfz6I8+sJ52F/W8dfG53ys/5zS//Lhy0PXPbKclykCCIk8bl6VcwyVpbWtGmAuQhj/thzi876dewJk5YxYsPIf9b7OwFdXWibXG56YkKxisiZPv5A9bfOcwKmV+MW/9prqMAPdaMYLr3DtLMUmq1CKXikWynfb3W8+ilJO9Xzf59TDF8moHOaZN5cwhAJ7OUTchAiLKzjokGYT8c=
    DOCKER_PASSWORD:
      secure: GCA2Xeoxx2WJJ64sKroj0fk9279SSVuG0bIT84ptcA/eH3XmFq3LPfN0oBdfvFKXz+HyDShMmXwErpZEnryK0Jxvifa406zcq2Q2oYmEBWdlo8o020/V/ZbJvOSdhSzOQr8OnvzwY0/oPA4vWpuu/tiyPTT1pBukRNx685tC2n63n76+lnInKyqWaagDIG+5uwP2fCHHe2JOLLBK8eMjviwqQRmqOUGeWvUmgAuNbmhrL91QrFZVFI24zwZSAq40/N3MjLAOT17HPP3bgNuKfWeowLcX86TrZhiQy+dt0h2bFjOOrm08Us9GQkJUJVJkDkA+PqcCgy2sA28hYTPDqwiO+mLt4nlB4dN9wRte6OJZvh0OS/+HGg1ENLF6Yr+PQax+ptCLtwE9mNZc6I6MxniTalh0Tz86bZ7ylKW/nKe5OkotUzpv8UTBINEhRAVTLuE2F0G9MwXpymBxyJa11vYRqXgxlhbp/3E7xZep//tSMwyprDv06e/n+uZW3hPWDZomxt4SaE7F/ZVyAYs0jODDr8zMsbB9j9b1QUuyfcgSMkIBJMPoZKEXRsEKAq20pZiwi7b/1vA0vOMnD1nVkzJMpT408Bnrp5uxSNq97RpAUaIZXRtgFDcobFHWzWj5t0r3PunF9/ZB7HyAEOvaybMf+owwPc0rf3N//LmsOYc=
