version: "3"

services:

    redis:
        image: redis:alpine
        ports:
            - "6379"
    celery:
        build: ./celery
        command: /sbin/init

    rworker:
        build: ./rworker
